"""vulnscan - Network vulnerability scanner | Copyright (c) 2026 Shpetim / Dardanex | MIT License"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

GENERATOR = {
    "tool": "vulnscan",
    "version": "1.0.0",
    "author": "Shpetim",
    "organization": "Dardanex",
    "website": "https://www.dardanex.com",
}


def severity_summary(cves_by_service: dict[str, list[dict[str, Any]]]) -> dict[str, int]:
    """Count results by NVD base severity."""
    counts = {name: 0 for name in ("CRITICAL", "HIGH", "MEDIUM", "LOW")}
    for findings in cves_by_service.values():
        for cve in findings:
            severity = str(cve.get("severity", "")).upper()
            if severity in counts:
                counts[severity] += 1
    return counts


def build_report(data: dict[str, Any]) -> dict[str, Any]:
    """Add calculated summary fields while preserving scan evidence."""
    result = dict(data)
    result["generator"] = dict(GENERATOR)
    result["summary"] = {"open_ports": len(data.get("ports", [])), "cves": severity_summary(data.get("cves", {}))}
    return result


def text_report(data: dict[str, Any]) -> str:
    """Render a compact report that remains useful in plain-text terminals."""
    lines = [
        "VULNSCAN REPORT",
        "=" * 60,
        f"Target: {data.get('target', 'N/A')}",
        f"Timestamp: {data.get('timestamp', 'N/A')}",
        "",
    ]
    dns = data.get("dns", {})
    lines += ["DNS", "-" * 3, f"IPv4: {', '.join(dns.get('ipv4', [])) or 'None'}", f"IPv6: {', '.join(dns.get('ipv6', [])) or 'None'}", "", "OPEN PORTS", "-" * 10]
    for port in data.get("ports", []):
        detail = " ".join(filter(None, [port.get("service"), port.get("product"), port.get("version")]))
        lines.append(
            f"{port.get('host', 'N/A')} {port.get('port', 'N/A')}/"
            f"{port.get('protocol', 'UNKNOWN')}  {detail or 'unknown'}"
        )
    if not data.get("ports"):
        lines.append("No open ports found.")
    lines += ["", "CVES", "-" * 4]
    for service, findings in data.get("cves", {}).items():
        lines.append(service + ":")
        for cve in findings:
            lines.append(
                f"  {cve.get('id', 'N/A')} "
                f"[{cve.get('severity', 'UNKNOWN')} {cve.get('score', 'N/A')}] "
                f"{cve.get('published', 'N/A')}"
            )
    if not data.get("cves"):
        lines.append("CVE lookup disabled or no versioned services found.")
    lines += ["", "HTTP SECURITY HEADERS", "-" * 21]
    for item in data.get("headers", []):
        lines.append(f"{item.get('url')}: {item.get('grade', 'ERROR')}")
        if item.get("error"):
            lines.append("  " + item["error"])
        for check in item.get("checks", []):
            if check.get("status", "UNKNOWN") != "present":
                lines.append(
                    f"  {check.get('header', 'N/A')}: {check.get('status', 'UNKNOWN')} "
                    f"— {check.get('recommendation', 'N/A')}"
                )
    summary = data.get("summary", {})
    lines += ["", "SUMMARY", "-" * 7, f"Open ports: {summary.get('open_ports', 0)}"]
    lines += [f"{key.title()} CVEs: {value}" for key, value in summary.get("cves", {}).items()]
    generator = data.get("generator", GENERATOR)
    lines += [
        "",
        "-" * 60,
        "Generated by "
        f"{generator.get('tool', 'vulnscan')} v{generator.get('version', 'N/A')} "
        f"| {generator.get('author', 'UNKNOWN')} / "
        f"{generator.get('organization', 'UNKNOWN')} "
        f"| {generator.get('website', 'N/A')}",
    ]
    return "\n".join(lines) + "\n"


def write_reports(data: dict[str, Any], output_dir: Path, output_format: str, stem: str) -> list[Path]:
    """Write selected formats and return their paths."""
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_stem = re.sub(r"[^A-Za-z0-9._-]", "_", stem)
    paths: list[Path] = []
    if output_format in {"txt", "both"}:
        path = output_dir / f"{safe_stem}.txt"
        path.write_text(text_report(data), encoding="utf-8")
        paths.append(path)
    if output_format in {"json", "both"}:
        path = output_dir / f"{safe_stem}.json"
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        paths.append(path)
    return paths
