"""vulnscan - Network vulnerability scanner | Copyright (c) 2026 Shpetim / Dardanex | MIT License"""

import json

from scanner.report import build_report, write_reports


def test_report_generation_writes_both_formats(tmp_path) -> None:
    report = build_report(
        {
            "target": "example.com",
            "timestamp": "2026-01-01T00:00:00Z",
            "dns": {"ipv4": [], "ipv6": []},
            "ports": [],
            "cves": {
                "service": [
                    {
                        "id": "CVE-2024-0001",
                        "severity": "HIGH",
                        "score": 8.1,
                        "published": "2024-01-01",
                        "description": "Test CVE",
                    }
                ]
            },
            "headers": [],
        }
    )
    paths = write_reports(report, tmp_path, "both", "scan_example")
    assert {path.suffix for path in paths} == {".txt", ".json"}
    assert report["summary"]["cves"]["HIGH"] == 1
    assert report["generator"]["author"] == "Shpetim"
    json_report = json.loads((tmp_path / "scan_example.json").read_text(encoding="utf-8"))
    assert json_report["generator"]["organization"] == "Dardanex"
    assert "Generated by vulnscan v1.0.0" in (tmp_path / "scan_example.txt").read_text(
        encoding="utf-8"
    )


def test_report_generation_handles_incomplete_cve(tmp_path) -> None:
    report = build_report(
        {
            "target": "example.com",
            "timestamp": "2026-01-01T00:00:00Z",
            "dns": {},
            "ports": [],
            "cves": {"service": [{"severity": "HIGH"}]},
            "headers": [],
        }
    )
    paths = write_reports(report, tmp_path, "both", "incomplete_cve")
    assert len(paths) == 2
    assert "N/A" in (tmp_path / "incomplete_cve.txt").read_text(encoding="utf-8")
